### ISSUE TITLE
npm run test tries to run cypress tests too, fails

### ISSUE THREAD

**Issue by tv42** [MicLeey/sveltekit-ory-starter#6]
Seems like jest needs to exclude cypress tests.

```
$ npm run test
> svelte-kit-ory-starter@0.0.1 test ...
> jest src

 PASS  src/lib/util/map-message.spec.ts
 FAIL  cypress/integration/register.spec.ts
  ● Test suite failed to run

    cypress/integration/register.spec.ts:7:3 - error TS2304: Cannot find name 'cy'.

    7   cy.visit('/auth/register').url().should('include', '?flow=');
        ~~
    cypress/integration/register.spec.ts:11:3 - error TS2304: Cannot find name 'cy'.

    11   cy.getByTestId(REGISTER_FIELDS.email).type('foo').should('have.value', 'foo');
         ~~
    cypress/integration/register.spec.ts:15:3 - error TS2304: Cannot find name 'cy'.

    15   cy.getByTestId(REGISTER_FIELDS.password).type('bar').should('have.value', 'bar');
         ~~
    cypress/integration/register.spec.ts:19:3 - error TS2304: Cannot find name 'cy'.

    19   cy.getByTestId(REGISTER_FIELDS.submit).contains('Register');
         ~~
    cypress/integration/register.spec.ts:23:3 - error TS2304: Cannot find name 'cy'.

    23   cy.register();
         ~~
    cypress/integration/register.spec.ts:28:3 - error TS2304: Cannot find name 'cy'.

    28   cy.register(email, password);
         ~~
    cypress/integration/register.spec.ts:31:3 - error TS2304: Cannot find name 'cy'.

    31   cy.waitForEmail(mailCriteria).then((verificationEmail: Email) => {
         ~~
    cypress/integration/register.spec.ts:32:4 - error TS2304: Cannot find name 'cy'.

    32    cy.document().invoke('write', verificationEmail.body);
          ~~
    cypress/integration/register.spec.ts:33:4 - error TS2304: Cannot find name 'cy'.

    33    cy.get('a').click();
          ~~
    cypress/integration/register.spec.ts:34:4 - error TS2304: Cannot find name 'cy'.

    34    cy.url().should('eq', urlWithExactPath('/'));
          ~~

 FAIL  cypress/integration/login.spec.ts
  ● Test suite failed to run

    cypress/integration/login.spec.ts:6:2 - error TS2304: Cannot find name 'before'.

    6  before(() => {
       ~~~~~~
    cypress/integration/login.spec.ts:7:3 - error TS2304: Cannot find name 'cy'.

    7   cy.register(registrationData.email, registrationData.password);
        ~~
    cypress/integration/login.spec.ts:8:3 - error TS2304: Cannot find name 'cy'.

    8   cy.logout();
        ~~
...
```

On a related note, the cypress tests hang for me when they try to talk to the kratos self-service API, but I haven't figured out why.

**Comment by MicLeey** [comment]
What OS & Node version are you on? Did not run into this. I excluded the cypress folder in the jest config in https://github.com/MicLeey/sveltekit-ory-starter/commit/34844780b2cd31ac035d7b03dcdcbf09b18a0c57, please let me know if that works for you.

> On a related note, the cypress tests hang for me when they try to talk to the kratos self-service API, but I haven't figured out why.

All of them? Can you interact with the self-service API manually or is it just the tests?

One thing I have noticed is that cypress input testing tends to be flaky when you run them in dev mode instead of on `npm run build` output.

**Comment by tv42** [comment]
> What OS & Node version are you on? Did not run into this. I excluded the cypress folder in the jest config in 3484478, please let me know if that works for you.

Linux (NixOS), tested with node v14.18.1 and v16.13.0.

Confirmed fixed in a58bb6442170224e082edc1be722dff62912cc5b.

> All of them? Can you interact with the self-service API manually or is it just the tests?

It seems to be all of them. I can manually log in & out fine in a normal browser. In cypress's interactive test runner I see form submits to the Kratos API simply never complete, while interactions with the SvelteKit app work fine.

> One thing I have noticed is that cypress input testing tends to be flaky when you run them in dev mode instead of on `npm run build` output.

`npm run build` && `npm run preview` didn't seem to help.

**Comment by MicLeey** [comment]
On Linux as well and verified working with the same node version, on Chrome 95 and Firefox 93, so perhaps it's some obscure network thing. 

Any errors when the request fails? Can you verify whether Kratos' redirects are working at least, by checking if the URL has a `flow=...` parameter in cypress flow tests?

**Comment by MicLeey** [comment]
Closing this as the original issue is fixed.

If your cypress tests keep hanging, please open a new issue with some more information and I'll try to help :)
Thanks for reporting!
